### ISSUE TITLE
Temperature chart overloads a CPU

### ISSUE THREAD

**Issue by saniaxxx** [avollkopf/craftbeerpi4#28]
I used cbpi for fermentation several days. During this time the sensor log file has accumulated more than 13000 lines. In this case, Web UI request data and overload CPU to 98%, and system worked very slowly. I truncated logfile and removed charts from UI - it resolved problem

**Comment by lalo-uy** [comment]
I have a cron job for cbpi3 that move to other folder lines more than 3
days old. Also the code that sends the data to ui plotting only put one
vale per m8nute, more than enough for am almos 4 day plot.

**Comment by avollkopf** [comment]
Are you talknig about the charts in the dashbaord?

This has been discussed in issue #20 and won't be changed. The CSV files are not ment for production 

1. CSV file limit is 1 Mb. Files are rotating which means you can have up to 4 files per sensor. -> 4 Mb
2. In case you are using one chart, 4 Mb need to be read per chart from a csv file
3. If you have for instance 4 charts, on a dashboard, the system needs to read 16 Mb every 10 seconds from csv and converts them, sends them to the UI. 

This ist not recommended and you should use either the analytics page or even better switch off the csv option in the settings as this may also screw your sd card.

I recommend to use the influxDB option instead (configuration on the settings page) and send all data to an influxdb database (currently only <2.0). This will allow you to have all data on a nice dashboard.

![Screenshot 2022-01-12 075420](https://user-images.githubusercontent.com/43980694/149078639-e7c04e46-5119-4822-b782-ae95c8e4bc8f.png)

The feature is implemented in 4.0.1.0 which is now the most recent version in the master branch.

I will update the documentation accordingly but close this as I won't change this now as already mentioned in #20
