### ISSUE TITLE
'Actor' object has no attribute 'get'

### ISSUE THREAD

**Issue by saniaxxx** [avollkopf/craftbeerpi4#36]
I get an error when use this method. But actor has property "instance" and I can call it directly
https://github.com/avollkopf/craftbeerpi4/blob/4f82dc85b34f3c9258950b710f34224d3bf00c0b/cbpi/api/base.py#L54
'Actor' object has no attribute 'get'
2022-01-29:12:14:44,445 ERROR    [base.py:49] Failed to read actor state in step - actor Dpx8WiBRSMmTabfTPNgzyx

**Comment by avollkopf** [comment]
I will look into it.

Meanwhile you can have a look at this code. That should work:

https://github.com/avollkopf/cbpi4-LCDisplay/blob/main/LCDisplay/__init__.py#L441

Most likely it needs to be changed to:
`return actor.instance.state`

**Comment by avollkopf** [comment]
Fixe in dev branch with this commit https://github.com/avollkopf/craftbeerpi4/commit/a7ddcdd30645c0661649225457f7918a07aa95a0
