### ISSUE TITLE
MQTT sends 2 or 4 identical messages when an Actor is updated

### ISSUE THREAD

**Issue by erlend71** [avollkopf/craftbeerpi4#37]
I'm running CBPI server 4.0.1.7 on a RPi4, and I am using an ESP32 with display and a rotary switch to send and receive state and power to a GPIO actor using MQTT
If I change state or power level on the server/frontend, two or four identical MQTT message are transmitted (messageid will update sequentially):
````
{"id": "QrfdzP7hdUjYEqm2ELCpsU", "name": "Boiler Heater", "type": "GPIOActor", "props": {"Topic": "cbpi/power_level", "SamplingTime": 2, "Inverted": "No", "GPIO": 18}, "state": true, "power": 60}
qos : 1, retain : false, cmd : publish, dup : false, topic : cbpi/actorupdate/QrfdzP7hdUjYEqm2ELCpsU, messageId : 49, length : 238
````

The same happens if I update state or power by sending this from my ESP32:
```
payload: 63
qos : 0, retain : false, cmd : publish, dup : false, topic : cbpi/actor/QrfdzP7hdUjYEqm2ELCpsU/power, messageId : , length : 43
```
CBPI will then respond with 2 or 4 identical messages with the new state/power as in my first example above. I have not managed to figure out any pattern regarding if 2 or 4 messages are sent. 
If I look in the logging output on CBPI, the duplicate messages produce these warnings:
```
2022-02-01:23:22:39,230 WARNING  [client.py:407] There are 11 pending publish calls.
2022-02-01:23:22:39,231 WARNING  [client.py:407] There are 12 pending publish calls.
```
This issue is of course not a big deal as everything's working just fine, but I just wanted to report and get this problem registered.

There is also some inconsistency when it comes to messages sent from CBPI with the 'retain' flag set, or maybe I'm not able to figure out how this is supposed to work (we're still talking about the same GPIO actor): 
If I reset my ESP32, it will receive the last MQTT message  with the retain flag set from the broker, which almost never is the same as I see on the frontend. Usually the received values are a few iterations old, for example I have to change power level or state on the frontend a few times before this will be sent from CBPI as a retained message.

**Comment by avollkopf** [comment]
I will look into it. Unfortunately, I am not an expert on mqtt. I was just trying to get this working. Which mqtt explorer are you using to identify the duplicated messages?

Which actor are you using? It could be that on and off is causing also a publish of the actor_update which is called by set_power in the actor controller.

**Comment by avollkopf** [comment]
It seems to be that the first `push_update` can be removed w/o causing any issues. This will cut the messages in half.

Then, the `off` command will ras only one essage, while the on command will still raise two messages. 
- one for switching the actor on, 
- the other one for setting the power

I need to dig a bit deeper on how this can be avoided w/o causing issues for various types of actors (w/ and W/o power settings)

**Comment by avollkopf** [comment]
@erlend71 I have updated the dev branch to V 4.0.1.10. This should reduce the messages 'significantly'. 

There was also a duplicated update in the sattelite controller when you trigger the power of a cbpi actor via mqtt.

There is still a duplicated message when you switch an actor on as it will be switched on and the power will be set. I need to dig a bit more into that.

I also need to read a bit more about the retain flag as I also have no idea on the details ....

**Comment by avollkopf** [comment]
I also managed to get rid of the duplicated messagen when switching the actors on -> dev branch 4.0.1.14
