### ISSUE TITLE
push message

### ISSUE THREAD

**Issue by dimontau** [avollkopf/craftbeerpi4#64]
Hello. In the next update, you can add a sound notification in the web interface when a push message appears. Or can it be enabled somewhere?
I haven't fully figured it all out yet.

**Comment by prash3r** [comment]
currently there is no way of playing a sound on a notification in the web browser. This feature request belongs to the frontend repository

[avollkopf/craftbeerpi4-ui](https://github.com/avollkopf/craftbeerpi4-ui) .

If you have or are willing to connect a buzzer to a GPIO pin of your Pi you can use this existing plugin to make a sound when a notification is triggered

[avollkopf/cbpi4-buzzer](https://github.com/avollkopf/cbpi4-buzzer)

**Comment by dimontau** [comment]
It would be good to solve this problem. Since I can’t constantly monitor the process, it was convenient to hear the sound from the browser.

**Comment by avollkopf** [comment]
As mentioned, this is something that would need to be implemented in the frontend and cannot be done in the server
