### ISSUE TITLE
plugin lifeguard

### ISSUE THREAD

**Issue by dimontau** [avollkopf/craftbeerpi4#66]
I've been testing the system for two weeks now. This is what I needed. I think the lifesaver plugin is sorely lacking. That is, you need a plug-in for a water leakage sensor on the floor. If water spilled water on the floor, the entire power unit was de-energized and the buzzer worked

**Comment by avollkopf** [comment]
As mentioned, you are requesting a plugin which needs to be written by someone from the community. This is not related to a server issue. There will be a discord channel pretty soon and you can add this plugin request there.
