### ISSUE TITLE
Access to Craftbeerpi4 by https (SSL)

### ISSUE THREAD

**Issue by WadjoResende** [avollkopf/craftbeerpi4#73]
Hi!
First, I would like to congratulate you to the program. Craftbeerpi is fantastic!
I installed Craftbeerpi4 via Docker container and I would like to access it over the internet on a certified domain (SSL), but the page does not open, leaving only a black screen.
Is there a way to configure the image to be able to open in https?
Thanks!

**Comment by lopelex** [comment]
https://github.com/avollkopf/craftbeerpi4-ui/pull/28

**Comment by avollkopf** [comment]
Since the PR has been merged, I am just wondering if this issue is still open. Can you please respond that we can close the issue.

**Comment by WadjoResende** [comment]
Sorry for not replying.  You can close it.  Thanks!

**Comment by avollkopf** [comment]
No worries. Thanks for the feedback. Will close it
