### ISSUE TITLE
Influx: Configurable measurement name

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4#80]
Currently the measurement name seems to be hardcoded to "measurement" (not the best choice, since this is a keyword in the Influx CLI). 
A Parameter to define the measurement name would be great. 

Also: it seems not to be mentioned in the doc that the measurement name is "measurement". I initially was looking for something like "cbpi" (as the MQTT Topic). 

Same request can applied to the MQTT root topic for CBPi.

**Comment by avollkopf** [comment]
Influxdb topic should be working with [this](https://github.com/avollkopf/craftbeerpi4/commit/2429ea63d1f8badbf32f8c9722a051ecafb04359) version

MQTT topics should be fix as there are too many dependencies. It has been documented [here](https://openbrewing.gitbook.io/craftbeerpi4_support/readme/craftbeerpi-4-server/mqtt-connectivity)
