### ISSUE TITLE
Suggestion: Timeout for HTTP Sensor

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4#81]
Enhancement Request:
When using the HTTP sensor, the last received value is shown. But the HTTP Source that is sending the data may be offline. So it is unknown how old the data is.
In this case an error message should be raised after a configured timeout to inform the operator that there is no incoming data from the HTTP Sensor.

I already changed the http_sensor of CBPI3 to meet this requirement and it was working stable for the last 5 years.
I attached the Sourcecode for CBPI3 http_sensor.
[http_sensor_with_timout_CBPI3.zip](https://github.com/avollkopf/craftbeerpi4-ui/files/10461336/http_sensor_with_timout_CBPI3.zip)

Would be great if s.o. could convert the CBPi3 solution to CBPi4. 

__init__.py

```# -*- coding: utf-8 -*-
import os
from subprocess import Popen, PIPE, call
from modules import cbpi
from modules.core.hardware import ActorBase, SensorPassive, SensorActive
import json
from flask import Blueprint, render_template, jsonify, request
from modules.core.props import Property

blueprint = Blueprint('http_sensor1', __name__)
cache = {}

@cbpi.sensor
class HTTPSensor(SensorActive):
    key = Property.Text(label="Key", configurable=True)
    iTimeout = Property.Number(label="Timeout", configurable=True, default_value=30, description="Timout Value in seconds. A notification will be displayed if the sensor has not sent a value in this time.")
    def execute(self):
        global cache
        bNotificationSent = False
        #Start Value: give the System 60 additional loops to receive the first value.
        counter = int(-60)
        sensortimeout = int(self.iTimeout)
        while self.is_running():
            try:
                counter = counter + 1
                value = cache.pop(self.key, None) 
                if value is not None:
                    self.data_received(value)
                    #Value received, reset counter
                    counter = 0
                    bNotificationSent = False
                if counter >= sensortimeout and not bNotificationSent:
					bNotificationSent = True
					msg = "Sensor: " + self.key
					cbpi.notify("HTTPSensor Timeout", msg, type="danger", timeout=None)
                if counter > sensortimeout and bNotificationSent:
					#Prevent Overflow of counter after long running time. Counter will stay at the same value after sending the message.
					counter = counter - 1
            except:
                pass
            self.api.socketio.sleep(1)

@blueprint.route('/<id>/<value>', methods=['GET'])
def set_temp(id, value):
    global cache
    cache[id] = value
    return ('', 204)

@cbpi.initalizer()
def init(cbpi):
    print "INITIALIZE HTTP SENSOR MODULE"
    cbpi.app.register_blueprint(blueprint, url_prefix='/api/httpsensor')
    print "READY"

**Comment by lalo-uy** [comment]
Very good. The same could be applied to mqtt sensors.

**Comment by avollkopf** [comment]
Theoretically possible. 

BUT: cbpi4 does not have the possibility to configure the notification with respect to display time. (I have not yet figured out how to adapt this in the UI).

The message would show up and vanish after 5 sec. Currently you will need to send yourself for instance a push notification. Would that be working?

**Comment by Admiraldr** [comment]
Would be ok. 
Or a configurable repeat interval that brings up the message regularly.

**Comment by avollkopf** [comment]
Check out this [one](https://github.com/avollkopf/craftbeerpi4/commit/47e3bcb5297565435349eaf175e2320397a68709).

Should be working even with confirmation button. Will look to add the name of the sensor instead of the id in the future.

**Comment by avollkopf** [comment]
- Added deactivation of notification via 0 timeout value
- Added function also to mqtt sensor
-> [development branch](https://github.com/avollkopf/craftbeerpi4/commit/85490cebc8610ed3cf86bf3a6820d5fd2a0d4997)

**Comment by avollkopf** [comment]
> May be a change in the temp background color. Then you can look at the chart and see when the flat start. El El vie, 20 de ene. de 2023 a la(s) 13:46, Alexander Vollkopf < ***@***.***> escribió:

Please have a look at the latest dev branch. Message will show up, and you need to confirm to remove t from the display. It'll show Sensor name and time of last successful data transfer
