### ISSUE TITLE
Docker: Installing Plugins as per Documentation fails.

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4#82]
I try to follow the instructions to run CBPi4 in a docker image as described here:
https://openbrewing.gitbook.io/craftbeerpi4_support/readme/server-installation#docker

I get into trouble when trying to create an image with plugins. 

In Step 1 it should be mentioned in the Dockerfile needs to be placed in an empty directory, because the "docker build" command takes every file in the current directory.
Once the Dockerfile is placed in a seperate Directory, it starts to runs fine.

Step 1 is downloading the image.

Step 2 Fails: RUN pip3 install --no-cache-dir cbpi4-system     && cbpi add cbpi4-system
It looks like, there is no "cbpi add <pluginname>" command.

```Step 2/8 : RUN pip3 install --no-cache-dir cbpi4-system     && cbpi add cbpi4-system
 ---> Running in b11d8269e1b9
Collecting cbpi4-system
  Downloading cbpi4-system-0.0.8.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: psutil>=5.9.0 in /opt/venv/lib/python3.9/site-packages (from cbpi4-system) (5.9.0)
Collecting gpiozero
  Downloading gpiozero-1.6.2-py2.py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.9/148.9 kB 3.8 MB/s eta 0:00:00
Collecting colorzero
  Downloading colorzero-2.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: setuptools in /opt/venv/lib/python3.9/site-packages (from colorzero->gpiozero->cbpi4-system) (65.6.3)
Building wheels for collected packages: cbpi4-system
  Building wheel for cbpi4-system (setup.py): started
  Building wheel for cbpi4-system (setup.py): finished with status 'done'
  Created wheel for cbpi4-system: filename=cbpi4_system-0.0.8-py3-none-any.whl size=16065 sha256=b170a8b50707214ba7784d7228bc981e22119f4d9c62c54fcb23e93c779b13a0
  Stored in directory: /tmp/pip-ephem-wheel-cache-xfm85_e1/wheels/24/2c/28/6cc147d68df5ac576cd3633f7544b98a4c1df2d1bef80ac6a9
Successfully built cbpi4-system
Installing collected packages: colorzero, gpiozero, cbpi4-system
Successfully installed cbpi4-system-0.0.8 colorzero-2.0 gpiozero-1.6.2
Usage: cbpi [OPTIONS] COMMAND [ARGS]...
Try 'cbpi --help' for help.

Error: No such command 'add'.
The command '/bin/sh -c pip3 install --no-cache-dir cbpi4-system     && cbpi add cbpi4-system' returned a non-zero code: 2
```

**Comment by Admiraldr** [comment]
Seens that in the example the backslash at the end of the RUN Line and den next Line must be deleted.
```
FROM ghcr.io/avollkopf/craftbeerpi4:latest

# Install plugins
RUN pip3 install --no-cache-dir cbpi4-system 
RUN pip3 install --no-cache-dir cbpi4-KettleSensor 
RUN pip3 install --no-cache-dir cbpi4-http-actor 
RUN pip3 install --no-cache-dir cbpi4-PIDBoil 
RUN pip3 install --no-cache-dir cbpi4-PID_Autotune 
RUN pip3 install --no-cache-dir cbpi4-buzzer

**Comment by avollkopf** [comment]
Seems to pretty old as cbpi add is not required for about 1 year . Will update documentation accordingly

**Comment by Admiraldr** [comment]
Further Documentation Notes: 

Also a Note that the Dockerfiule needs to be placed in a seperate Directory and that the "." in 

```
docker build . -t craftbeerpiwithplugins:latest
```
can be replaced by the directorys name when called from the users home directory would be helpful for docker newbies. 

Example: 
```
mkdir cbpiwithplugins
nano cbpiwithplugins/Dockerfile
<insert code in nano as per the example and save the file>
docker build cbpiwithplugins -t craftbeerpiwithplugins:latest
```

Finally: run the image with:
```
docker run -d -v "$(pwd)/config:/cbpi/config" -p 8000:8000 craftbeerpiwithplugins:latest
```
The "config" folder has to be created as described as in the 
https://openbrewing.gitbook.io/craftbeerpi4_support/readme/server-installation#preparing-configuration-data
part in advance.

Additional Info that would be helpful: instead of :latest in the Dockerfile also :dev can be used to get the development version.
