### ISSUE TITLE
Correction Description on Hardware Config Page

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4#83]
![image](https://user-images.githubusercontent.com/31703558/215124703-e6f2dc2e-b2b9-4cfc-922a-d62ed9fc7b59.png)

```
Cooler Offset On
Offset as decimal number when the cooler is switched on. Should be greater then 'CoolerOffsetOff'. For example a value of 2 switches on the cooler if the current temperature is 2 degrees **below** the target temperature
```
Shouldn't this be "_**above** the target temperature_"? Probably Copy & Paste Error from Heater description.

**Comment by avollkopf** [comment]
Good Catch. [Fixed](https://github.com/avollkopf/craftbeerpi4/commit/853920be6d27feee3a6e64756e595ed93d485094)
