### ISSUE TITLE
Grafana Chart will not connect

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4#84]
I am configuring the Grafana Chart object as required (anonymized a few characters):
URL (Basically I stole that from Grafna -> Share Panel -> Embed)
http://192.168.0.NNN:3000/d-solo/m01U*****/garung-overview

![image](https://user-images.githubusercontent.com/31703558/215142172-f6e3579a-3188-4ad4-b4e5-6e35408ead17.png)

If I call the URL in a way in a web browser:
http://192.168.0.NNN:3000/d-solo/m01U*****/garung-overview?panelId=2
everything is displayed correctly. 
![image](https://user-images.githubusercontent.com/31703558/215141510-588b1c74-7c74-4367-9124-907a37dfa230.png)

In the Dashboard:
![image](https://user-images.githubusercontent.com/31703558/215141803-515be13b-4ddf-4ce6-965e-99a2f6d04ba3.png)

I just noted in the Configuration panel that then "Panel Id" heading is written "panelID" instead of "panelId" (which is required by Grafana.). Probably there is just a capital D in the code instead of a lower case "d". (But that's just a guess.)

**Comment by avollkopf** [comment]
http://192.168.163.105:3000/d/m5Lx6uYnz/craftbeerpi-4?orgId=1&viewPanel=7

--> URL: http://192.168.163.105:3000/d-solo/m5Lx6uYnz/craftbeerpi-4
--> panelID: 7

Working here.

I don't use them typically. But anyway nothing for the python server but the UI or better documentation

**Comment by Admiraldr** [comment]
Does the "Image Renderer Plugin" needs to be installed in Grafana?

**Comment by Admiraldr** [comment]
Got it:
In /etc/grafana/grafana.ini 
Option allow_embedding = true.
https://community.grafana.com/t/share-iframe-unatuthenticated-true-but-refuses-to-connect/60118

Important: remove the ";" from the beginning of the line, since this disables the line. 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#remove-comments-in-the-ini-files
