### ISSUE TITLE
Deletion of log files not working with rotatingfilehandler in log_file_cotnroller

### ISSUE THREAD

**Issue by avollkopf** [avollkopf/craftbeerpi4#85]
@phylax2020 It seems to be that the #57 created an issue with deletion of log files from the analytis page -> clear log function in log file controller. Not sure if you have an idea. The log files are locked and cannot be deleted via os.remove().

Maybe you have an idea on how to close / stop the particular filehandler to remove or clear the corresponding logfiles.

**Comment by avollkopf** [comment]
This [test](https://github.com/avollkopf/craftbeerpi4/commit/90f94525be32e42a41040174d3d8ef44fc732480) seems to work

**Comment by phylax2020** [comment]
I tested it based on your latest development branch and it worked fine!

**Comment by avollkopf** [comment]
ok, I alo think it is working now with the latest change
