### ISSUE TITLE
cbpi create not possible with the new version 4.1

### ISSUE THREAD

**Issue by PhilippRuppert** [avollkopf/craftbeerpi4#87]
Hello,
I have updated the CraftbeerPI version on my Raspberry to the 4.1 a few days ago. Since then, unfortunately, I can not create a new plugin. I get the following output in the shell.

pi@cbpi:~ $ sudo cbpi create
---------------------
Welcome to CBPi
---------------------
config folder path :   ./config
logs folder path   :   /home/pi/logs
Plugin Creation

Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/cli.py", line 289, in create
    context.obj.plugin_create()
  File "/usr/local/lib/python3.9/dist-packages/cbpi/cli.py", line 89, in plugin_create
    answers = prompt(questions)
  File "/usr/local/lib/python3.9/dist-packages/inquirer/prompt.py", line 11, in prompt
    answers[question.name] = render.render(question, answers)
  File "/usr/local/lib/python3.9/dist-packages/inquirer/render/console/__init__.py", line 27, in render
    question.answers = answers or {}
AttributeError: 'dict' object has no attribute 'answers'

Unfortunately, the output tells me nothing. Is this a bug ? 
Thank you very much in advance.

**Comment by prash3r** [comment]
this could be a bug, at least it should have a better Error message.

Did you provide a plugin name with the `cbpi create` command? The command should be something like `cbpi create newFeaturePluginName`. If you did provide a plugin name this is a bug and i will look at it tonight. if not then please try to provide a name with the command as mentioned in the docs [plugin creation documentation](https://craftbeerpi.gitbook.io/craftbeerpi4/development), please.

I will add a better handling of this error at some point in the future, it shouldn't fail like this.

**Comment by PhilippRuppert** [comment]
Hi and thanks for the quick reply!  Unfortunately, directly with the specification of the name only the message appears: "Error: Got unexpected extra argument".

pi@cbpi:~ $ sudo cbpi create Gaerspund
---------------------
Welcome to CBPi
---------------------
config folder path :   ./config
logs folder path   :   /home/pi/logs
Usage: cbpi create [OPTIONS]
Try 'cbpi create --help' for help.

Error: Got unexpected extra argument (Gaerspund)

If I remember correctly then this was in the previous version a "kind of wizard" where the name was queried. (is also described in the documentation)

**Comment by prash3r** [comment]
This was a bug, thank you for reporting it. I created a pull request with fix. For you to be able to continue today you can **unzip** this folder [cbpi4-Gaerspund.zip](https://github.com/avollkopf/craftbeerpi4/files/10677687/cbpi4-Gaerspund.zip), place it on your pi and and continue according to the [docs at step 3](https://craftbeerpi.gitbook.io/craftbeerpi4/development#3.-add-custom-code).

This issue can be closed when #88 is merged.

**Comment by PhilippRuppert** [comment]
Hi, just installed the plugin from you. Worked without any problems.

Thanks again & have a nice evening.

**Comment by avollkopf** [comment]
fixed with pr#88
